language: go
go:
    - "1.15"

matrix:
    include:
    -   os: linux
        script:
            - ./demo.sh
    -   os: osx
        script:
            - ./demo.sh
    -   os: windows
        script:
            - cmd.exe //C "demo.bat"
