language: go
go:
    - "1.15"
allow_failures:
    - os: windows
matrix:
    include:
    -   os: linux
        script:
            - ./demo.sh
    -   os: osx
        script:
            - ./demo.sh
    -   os: windows
        script:
            - powershell -Command ./demo.bat
